export const stargazers = [
	"Charmine Pleavin",
	"Winfred Housby",
	"Ethelbert Vignal",
	"Maribel Petegrew",
	"Pyotr Allso",
	"Stephine Swainsbury",
	"Russell De Biaggi",
	"Orion Ovise",
	"Salim Midgley",
	"Dominique Tyhurst",
	"Emmit Ramsell",
	"Jacqueline Ivermee",
	"Evey Shea",
	"Floyd McFayden",
	"Odele Georg",
	"Franciskus Pellingar",
	"Lorenza Sterland",
	"Jarrett Jacklings",
	"Maud Chasle",
	"Florina Windless",
	"Charmine Pleavin",
	"Winfred Housby",
	"Ethelbert Vignal",
	"Maribel Petegrew",
	"Pyotr Allso",
	"Stephine Swainsbury",
	"Russell De Biaggi",
	"Orion Ovise",
	"Salim Midgley",
	"Dominique Tyhurst",
	"Emmit Ramsell",
	"Jacqueline Ivermee",
	"Evey Shea",
	"Floyd McFayden",
	"Odele Georg",
	"Franciskus Pellingar",
	"Lorenza Sterland",
	"Jarrett Jacklings",
	"Maud Chasle",
	"Florina Windless",
].map((name, index) => ({
	id: index,
	initials: name
		.split(" ")
		.map((p) => p[0])
		.join(""),
	name,
	color: `hsl(${index * 100}, 50%, 50%)`,
}));

export const links = [
	"Home",
	"World",
	"Politics",
	"Business",
	"Opinion",
	"Science",
	"Health",
	"Sports",
	"Arts",
	"Books",
	"Style",
	"Food",
	"Travel",
].map((title, index) => ({
	id: index,
	title,
	url: undefined,
}));

export const songs = [
	{
		title: "Dribble",
		artist: "Sycco",
		coverArt: "/assets/examples/playlist/sycco-dribble.jpg",
	},
	{
		title: "Idontknow",
		artist: "Jamie xx",
		coverArt: "/assets/examples/playlist/jamiexx-idontknow.jpg",
	},
	{
		title: "As It Was",
		artist: "Harry Styles",
		coverArt: "/assets/examples/playlist/harrystyles-asitwas.jpg",
	},
	{
		title: "Remind Me",
		artist: "High Contrast",
		coverArt: "/assets/examples/playlist/highcontrast-remindme.jpg",
	},
	{
		title: "Rollin' & Scratchin'",
		artist: "Daft Punk",
		coverArt: "/assets/examples/playlist/daftpunk-rollinandscratchin.jpg",
	},
	{
		title: "Glue",
		artist: "Bicep",
		coverArt: "/assets/examples/playlist/bicep-glue.jpg",
	},
].map((song, index) => ({
	...song,
	id: index,
	spotifyLink: "https://open.spotify.com/playlist/1KQ0ofHhPeQ20lS8C0B5Es",
}));
